### ISSUE TITLE
PageNumber and SuggestedCpcForPageOne do not match backend

### ISSUE THREAD

**Issue by Nugz** [ecg-icas/icas#1]
The info shown in suggestedCpcForPageOne and pageNumber is different from the info I see if I log into the account on admarkt.marktplaats.nl.﻿

Example:
AdId: 1015549792
API results: page 10 / cpc 4
backend: page 1540 / cpc 0,33

**Comment by marcselman** [comment]
I've noticed this as wel. The values are useless if they are not valid. We want to show our customers the same data as visible in the Admarkt backend but right now that's not possible.

**Comment by magiconair** [comment]
We are working on that as well.

**Comment by magiconair** [comment]
We have found the issue and it should be fixed in the next release.

**Comment by magiconair** [comment]
This has been fixed in the release 6686e8e37d from today.
