### ISSUE TITLE
Pausing an add with enough budget results in an "insufficient budget" error

### ISSUE THREAD

**Issue by kasabov** [ecg-icas/icas#10]
Performing "PUT /ad/{id}/status/PAUSED" on an ad which has enough budget results in:
[{
    "code":2019,
    "text":"ad status change not possible due to insufficient budget",
    "msg":"Cannot change ad status to PAUSED from ACTIVE due to insufficient budget",
    "field":"status",
    "arg":"PAUSED"
}]

Expected response is "200 OK".

**Comment by magiconair** [comment]
We've deployed a fix to the sandbox environment.

**Comment by magiconair** [comment]
Fix is live on production.
