### ISSUE TITLE
Requesting performance report using "read" scope fails with an "401 Unauthorized" error

### ISSUE THREAD

**Issue by kasabov** [ecg-icas/icas#11]
Retrieve an ad performance report should be possible for an authenticated user with a "read" scope. However, the API returns:
[{
    "code":1003,
    "text":"access denied",
    "msg":"You require the 'write' scope to access this resource",
    "field":"write",
    "arg":"scope"
}]

**Comment by magiconair** [comment]
We've deployed a fix to the sandbox

**Comment by magiconair** [comment]
Fix is live on production.
