### ISSUE TITLE
Getting client id and secret for https://admarkt.kijiji.ca

### ISSUE THREAD

**Issue by LingaTigeen** [ecg-icas/icas#28]
Hello, Could you please help me how to get the client id and secret for the authentication for https://admarkt.kijiji.ca? I didn't found anything related to that in the https://admarkt.kijiji.ca . Or in any other ways I can authenticate. Thanks

**Comment by twessling-icas** [comment]
Please contact Kijiji.ca for this, they will be able to get you started.
