### ISSUE TITLE
ShippingCosts are times ten!

### ISSUE THREAD

**Issue by marcselman** [ecg-icas/icas#3]
When supplying shipping costs, the value on Marktplaats is ten times the provided value.
For example I place an ad with 495 (cent) as value and it's displayed on Marktplaats as 49,50 (euro).

Also, when not supplying shipping costs the displayed value is -1.

**Comment by magiconair** [comment]
We're already working on a fix. Should go live today.

**Comment by magiconair** [comment]
The fix is live.

**Comment by marcselman** [comment]
Thanks for the quick fix!
