### ISSUE TITLE
Images not posting correctly

### ISSUE THREAD

**Issue by Nugz** [ecg-icas/icas#5]
Example ad Id: 1017433652

When posting an ad (ad may have been posted before), the return i get from the images is status ok, but the return URLs are:
[links] => stdClass Object
                        (
[64x64] => //i.marktplaats.com/null  
[726x726] => //i.marktplaats.com/null  
 [147x147] => //i.marktplaats.com/null  
[1024x1024] => //i.marktplaats.com/null  
[358x358] => //i.marktplaats.com/null                         )

Also the backend is showing no image

**Comment by magiconair** [comment]
I had a look and for this image we got a 403 Forbidden when trying to download it. Nevertheless, the image shouldn't be listed as OK. I'm going to check why that happened. Please try to resubmit the ad once the 403 problem is fixed.

```
Error fetching image from http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/American_Audio_XLT_2000_PA_eindversterker_front_view.jpg. Last status code 403. Giving up.
```

**Comment by Nugz** [comment]
Seems to be a firewall problem. Any IP adress we can tell our client to whitelist?

**Comment by twessling-icas** [comment]
Hi, please make sure the following two IP addresses are whitelisted:
5.255.156.126
5.255.156.110

**Comment by Nugz** [comment]
Hi. Our client whitelisted the IP addresses you listed, but the same error is still happening.
They checked their server logs and are only seeing 200 OK status as response to the image requests.

**Comment by magiconair** [comment]
When did you try this? I see something like 7300 failed requests from last Friday, 6 Feb 2015 between 10:30 and 12:30. Most of these requests failed with a 403 Forbidden.

However, when I try downloading some of these images now via the proxy 5.255.156.126 it all works. So my guess is still that the customer hadn't whitelisted the above IP addresses on Friday, 6 Feb 2015 when you tried placing the ads again. Unfortunately, I don't have the proxy logs from last Friday anymore. Can you check with the customer whether his access logs show a 200 OK for these requests? 

Here are some examples:

```
Feb 6 10:25:48 http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/Maglite_ML100_LED_2C_LED-zaklamp_met_2x_C-batterijen_1.jpg 403
Feb 6 10:25:48 http://static.bax-shop.nl/image/product/5388/129645/48ea2821/Behringer_1C-BK_passieve_monitor_set_1.jpg 403
Feb 6 10:25:49 http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/R15554K_4.jpg 403
Feb 6 10:25:49 http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/Meinl_Classics_Custom_14-16-20_bekkenset_met_koffer.jpg 403
Feb 6 10:25:49 http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/Nino_Percussie_NINO17Y-BK_kunststof_bongo_geel_01.jpg 403
Feb 6 10:25:50 http://static.bax-shop.nl/image/product/49017/163954/0fe327a3/Audioquest_Cinnamon-USB-kabel-0-75m.jpg 403
Feb 6 10:25:50 http://static.bax-shop.nl/components/com_virtuemart/shop_image/product/ELECTRO_VOICE_TX2181_3919.jpg 403
Feb 6 12:19:02 http://static.bax-shop.nl/image/product/88396/202497/f01012ef/apogee_mic_96k_microfoon_voor_ipad 404
Feb 6 12:20:33 http://static.bax-shop.nl/image/product/25978/274287/85e21017/DB_TECHNOLOGIES_CROMO_12+_2552b.jpg 404
Feb 6 12:23:47 http://static.bax-shop.nl/image/product/155005/307020/4ef1d0fb/BenQ_WH1070+W_totaal_01.jpg 404
```

If I look at the failures from 6 Feb 2015 the distribution is as follows:

```
$ awk '{print $5;}' static.bax-shop.nl-06-Feb-2015.txt| sort | uniq -c
   7377 403
     20 404
```

Also, I think I have found the source of the OK/null problem which IMO is still just a symptom of the 403 Forbidden problem. The correct status should have been ERROR with no image. I'll fix that tomorrow.

**Comment by Nugz** [comment]
I tried the same thing yesterday and today just now and still gave the same result. This is also the only clilent experiencing this kind of issue.

**Comment by magiconair** [comment]
I can see a single request today at 16:16:

```
 TCP_MISS/200 399 HEAD http://static.bax-shop.nl/image/product/48656/163593/158e5637/Europalms_Halloween_engel1.jpg - HIER_DIRECT/79.99.129.52 image/jpeg
TCP_MEM_HIT/200 406 HEAD http://static.bax-shop.nl/image/product/48656/163593/158e5637/Europalms_Halloween_engel1.jpg - HIER_NONE/- image/jpeg
```

Hmm, the response does not contain a Last-Modified and no Etag header. That might be an indication on where to look.

**Comment by magiconair** [comment]
I think we've found it. It was indeed the missing Etag and Last-Modified header which caused the images not be downloaded. This also explains why only this customer has this issue. Please note that we are using both Etag and Last-Modified for detecting whether there was a change in the image. If both headers are missing then we must download the image every time even when nothing has changed. This increases the latency in the update call. I advise to provide at least one of the two headers in the response.

We're going to test that in the morning and I expect the fix to go live today.

**Comment by Nugz** [comment]
Alright thnx! I'll pass along the information, as updating the images everything is not something either of us wants I think.

**Comment by magiconair** [comment]
Fix is live. Please test.

**Comment by Nugz** [comment]
Yes seems to be working! thanks a lot!

**Comment by magiconair** [comment]
Cool. Closing then
